#!/bin/bash

if [ $# -eq 0 ]
then
	echo "Usage: `basename $0` <tag|file.rc>" >&2
	ls *.rc
	exit 1
fi
if [ -e "$1" ] 
then
	script -fac "msfconsole -L -r $1" "`basename $1 .rc`-`date +%Y-%m-%d_%H:%M`.log"
else
	script -fac "msfconsole -L" "$1-`date +%Y-%m-%d_%H:%M`.log"
fi
